server:
  port: 8084

spring:
  application:
    name: emailservice
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/email-service-management?createDatabaseIfNotExist=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host:
    port:
    username:
    password:
  email:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

queue:
  name: default.email

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

